# Generated by Django 3.1 on 2020-08-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='email',
            field=models.EmailField(max_length=75),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='name',
            field=models.CharField(max_length=42),
        ),
    ]
