# Generated by Django 3.1 on 2020-08-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurseryapp', '0002_auto_20200810_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbluser',
            name='password',
        ),
    ]
