# Generated by Django 3.1 on 2020-08-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseryapp', '0003_remove_tbluser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='password',
            field=models.CharField(default=123, max_length=254),
            preserve_default=False,
        ),
    ]
