# Generated by Django 3.1 on 2020-08-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurseryapp', '0005_auto_20200811_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblplants',
            old_name='email',
            new_name='user',
        ),
    ]
