# Generated by Django 3.1 on 2020-08-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseryapp', '0008_tblreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblreg',
            name='user',
        ),
        migrations.AddField(
            model_name='tblreg',
            name='user_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
