# Generated by Django 3.1 on 2020-08-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurseryapp', '0009_auto_20200811_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblorder',
            old_name='name',
            new_name='customer_name',
        ),
    ]
