# Generated by Django 3.1 on 2020-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseryapp', '0010_auto_20200811_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblorder',
            name='order_status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
